### ISSUE TITLE
Server: Missing MOVIES_API and MOVIES_KEY

### ISSUE THREAD

**Issue by jrichardsz** [ridhwaans/homehost#18]
I tried to start the server using the readme: `npx prisma migrate dev`

I got this error:

```
Generating data for Movies...
GET: /foo/bar/like-netflix/movies/kate 597891.mkv
url: https://undefined/movie/597891?api_key=undefined&append_to_response=images,credits,similar
There was a problem adding this movie TypeError: Cannot read property 'status' of undefined
    at getMovieMetaData (/tmp/workspace/homehost/server/models/index.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async upsertManyMovies (/tmp/workspace/homehost/server/jobs/index.js:80:20)
    at async sync (/tmp/workspace/homehost/server/jobs/index.js:55:27)
```

My server env is:

```
TMDB_KEY = '47422a2813d47422a2813d'
SPOTIFY_CLIENT_ID = '<client_id>'
SPOTIFY_CLIENT_SECRET = '<client_secret>'

MOVIES_PATH = '/var/tmp/lisu/like-netflix/movies'
TV_PATH = '/opt/tv/directory'
MUSIC_PATH = '/opt/music/directory'

DATABASE_URL = 'file:./data/media.db'
CLIENT_BASE_URL = 'http://192.168.A.B:3000'
```
## Research

I found that the error is trowed in this file:

homehost/server/services/metadata.js

```
if (item.type == Type.Movie){
    request_url = `https://${process.env.MOVIES_API}/movie/${item.id}?api_key=${process.env.MOVIES_KEY}&append_to_response=images,credits,similar`
}
```

So my question is, what are the expected values for MOVIES_API and MOVIES_KEY?

Thanks

**Comment by jrichardsz** [comment]
Reviewing and with some intuition

![image](https://user-images.githubusercontent.com/3322836/134264210-13ab4156-0d2b-4187-8d53-639a118e3781.png)

I found the values:

```
MOVIES_API = api.themoviedb.org/3
MOVIES_KEY = 81*****e0b
```
**MOVIES_KEY** is the TMDB API KEY

Whit these values I don't see any error in the log but when I try to load the web, there is nothing to see :(

![image](https://user-images.githubusercontent.com/3322836/134264482-aee41ee1-315c-43ad-99a4-8380499e74b1.png)

This is the log when web page try to query something:

```
(node:24817) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at format (/tmp/workspace/homehost/server/utils/index.js:15:21)
    at getRandomMovie (/tmp/workspace/homehost/server/data/index.js:348:10)
    at async getRandomMovieOrTVShow (/tmp/workspace/homehost/server/data/index.js:336:31)
    at async /tmp/workspace/homehost/server/routes/index.js:232:25
(Use `node --trace-warnings ...` to show where the warning was created)
```

What I'm doing wrong?

**Comment by jrichardsz** [comment]
I was able to run everything:

![image](https://user-images.githubusercontent.com/3322836/134392774-14987459-4832-4f98-8fe8-89938ef8b3db.png)

But when I try to watch a video, I got this error:

![image](https://user-images.githubusercontent.com/3322836/134393020-7efeb8f6-67eb-4d10-8928-042181ec7acd.png)

I will create another issue with this new error.

## Steps to startup

- create an api key in tmdb service: https://stackoverflow.com/a/31047912/3957754
- choose some movies in the tmdb web and store its movie-id
  - For example in this movie https://www.themoviedb.org/tv/1402-the-walking-dead the movie-id is **1402**. You can use these: 'kate 597891.mkv', 'shang-chi-and-the-legend-of-the-ten-rings 566525.mkv', 'the-suicide-squad 436969.mkv'
- in your local disk, create a folder and put 3 videos (mkv/mp4). Rename them setting the movie-id + space + whatever. Example : **1402 another movie.mkv** 
- As in this test, probably you cannot a spotify account or videos for tv, we are using only movies. If this is your case, modify this [line](https://github.com/ridhwaans/homehost/blob/09dbcaa6c252a7822847f27d282d28fa1e190fbc/client/src/hooks/useSlide.js#L22) in the client to render just movies: 
  - `if (containerRef.current && containerRef.current.firstChild && data) {`  
- npm install in server and client folder
- open 3 shells and export these variables. Note the use of the local ip in **CLIENT_BASE_URL** variables:

```
export REACT_APP_IMAGE_BASE="https://image.tmdb.org/t/p/"
export REACT_APP_TMDB_BASE="https://www.imdb.com/title/"
export TMDB_KEY='811****ce0b'
export SPOTIFY_CLIENT_ID='<client_id>'
export SPOTIFY_CLIENT_SECRET='<client_secret>'
export MOVIES_PATH='/foo/bar/storage/movies'
export TV_PATH='/opt/tv/directory'
export MUSIC_PATH='/opt/music/directory'
export DATABASE_URL='file:./data/media.db'
export CLIENT_BASE_URL='http://192.168.A.B:3000'
export MOVIES_API=api.themoviedb.org/3
export MOVIES_KEY=811****ce0b
```

- create the database running `npx prisma migrate dev` in the server folder, using one of the previous opened shells
- startup the prisma server running `npx prisma studio` in the server,  using one of the previous opened shells
- startup the home-host server running `npm run dev`, using one of the previous opened shells
- startup the home-host web client running `npm run start`, using one of the previous opened shells
- an url will be opened in your default browser. Change the localhost in the url by your local ip

## Coming soon

- I will perform a PR with Docker docker-compose alternative
- Create an issue related to video load error
- Create an issue to enable or disable categories: movies, tvs, songs. In this version, if you cannot pass all of categories (videos/songa on your local disk), an error is throwed. That why a react modification is required in the previous steps
